repos:
  - repo: https://github.com/python/black
    rev: 22.1.0
    hooks:
      - id: black
        args: ['--line-length=120']
        additional_dependencies: ['click==8.0.4']
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ['--ignore=E203,W503', '--max-line-length=120']
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort
        args: ['-m3', '-tc']
