name: elephantbook
channels:
  - conda-forge
dependencies:
  - python==3.10.*
  - pip
  - git
  - celery
  - django-celery-beat
  - django-celery-results
  - django-drf-filepond
  - django-extensions
  - django-multiselectfield
  - django-tables2
  - django==4.0.4
  - djangorestframework
  - gunicorn
  - ipywidgets
  - jupyterlab
  - numpy
  - pandas
  - pillow
  - pre-commit
  - psycopg2
  - pycocotools
  - pytorch
  - redis-py
  - requests
  - torchvision
  - tqdm
  - pip:
    - django-polymorphic
    - rcos-match==0.3.0
  
  # Required for YOLOv5:
  - fastai::opencv-python-headless # Headless because docker image is missing libGL.so.1
  - matplotlib
  - seaborn
